/**
 * @description 路由相关
 *  */
// 修改路由
export const CHANGE_ROUTE = 'CHANGE/ROUTE';
// 修改loading状态
export const CHANGE_LOADING = 'CHANGE/LOADING';
// 修改 headername
export const UPDATE_HEADERNAME = 'UPDATE/HEADERNAME';

// 行李销售
export const BS_RECEIVE_QUERYSTROKE = 'BS_RECEIVE_QUERYSTROKE';
export const BS_RECEIVE_QUERYPRODUCT = 'BS_RECEIVE_QUERYPRODUCT';
export const BS_RECEIVE_CREATORDER = 'BS_RECEIVE_CREATORDER';
export const BS_RECEIVE_TOPAYANCLORDER = 'BS_RECEIVE_TOPAYANCLORDER';
export const BS_RECEIVE_QUERYBAGPAYSTATUS = 'BS_RECEIVE_QUERYBAGPAYSTATUS';
export const BS_RECEIVE_QUERYBAGORDERSTATUS = 'BS_RECEIVE_QUERYBAGORDERSTATUS';
export const BS_RECEIVE_QUERYANCLORDERLIST = 'BS_RECEIVE_QUERYANCLORDERLIST';
export const BS_RECEIVE_REFUNDANCLORDER = 'BS_RECEIVE_REFUNDANCLORDER';


export const BS_SAVE_IDNO = 'BS_SAVE_IDNO';
export const BS_SAVE_SELECTSTROKE = 'BS_SAVE_SELECTSTROKE';
export const BS_SAVE_SELECTBAGGAGE = 'BS_SAVE_SELECTBAGGAGE';

// 机票
export const TS_RECEIVE_QUERYFLIGHT = 'TS_RECEIVE_QUERYFLIGHT';
export const TS_RECEIVE_PRICECALENDER = 'TS_RECEIVE_PRICECALENDER';
export const TS_RECEIVE_AIRPORTLIST = 'TS_RECEIVE_AIRPORTLIST';
export const TS_RECEIVE_VERIFYCONTACT = 'TS_RECEIVE_VERIFYCONTACT';
export const TS_RECEIVE_ANCILSEARCH = 'TS_RECEIVE_ANCILSEARCH';
export const TS_RECEIVE_VERIFYRES = 'TS_RECEIVE_VERIFYRES';
export const TS_RECEIVE_ORDERCONFIRMRES = 'TS_RECEIVE_ORDERCONFIRMRES';
export const TS_RECEIVE_CREATEORDER = 'TS_RECEIVE_CREATEORDER';
export const TS_RECEIVE_QUERYPAYSTATUS = 'TS_RECEIVE_QUERYPAYSTATUS';
export const TS_RECEIVE_QUERYORDERSTATUS = 'TS_RECEIVE_QUERYORDERSTATUS';
export const TS_RECEIVE_TOPAYANCLORDER = 'TS_RECEIVE_TOPAYANCLORDER';
export const TS_RECEIVE_MERGEPASSENGER = 'TS_RECEIVE_MERGEPASSENGER';



export const TS_SAVE_PASSENGERSELECTED = 'TS_SAVE_PASSENGERSELECTED';
export const TS_SAVE_PASSENGER_WILLBE_EDITED = 'TS_SAVE_PASSENGER_WILLBE_EDITED';
export const TS_SAVE_SEARCH_FLIGHT_PARAMS = 'TS_SAVE_SEARCH_FLIGHT_PARAMS';
export const TS_SAVE_GO_FLIGHT_INFOS = 'TS_SAVE_GO_FLIGHT_INFOS';
export const TS_SAVE_RE_FLIGHT_INFOS = 'TS_SAVE_RE_FLIGHT_INFOS';

//订单详情
export const TO_SAVE_TICKETORDER_DETAIL_INFO = 'TO_SAVE_TICKETORDER_DETAIL_INFO'
//退票相关
export const TO_SAVE_ORDER_REFUND_CHECKED_PSG = 'TO_SAVE_ORDER_REFUND_CHECKED_PSG'
//改升相关
export const TO_SAVE_ORDER_CHANGE_CHECKED_PSG = 'TO_SAVE_ORDER_CHANGE_CHECKED_PSG'
export const TO_SAVE_ORDER_CHANGE_CHECKED_FLIGHT = 'TO_SAVE_ORDER_CHANGE_CHECKED_FLIGHT'
