export const test = {'commonRes':{'isOk':true},'orderDetail':{'bussinessCode':'H5','canBuyAncillary':'true','canCancelSeat':'false','canChange':'true','canChooseSeat':'false','canRefund':'true','components':{'AIR':{'count':'3','goItinerarys':[{'aircraftType':'73U','arrDate':'2019-09-01','arrTime':'09:50','bookClass':'J','brandInfo':{'brandCode':'HLY','brandName':'欢乐抢','brandPolicy':{'changeRegular':' 航班规定离站时间前7天（含）之前提出,收取客票价50%的变更费; 航班规定离站时间前7天至72小时（含）之内提出,收取客票价60%的变更费; 航班规定离站时间前72小时至4小时（含）之内提出,收取客票价80%的变更费; 航班规定离站时间前4小时之后提出,收取客票价90%的变更费。 ','checkBaggageDesc':'无免费托运行李额','handBaggage':'10KG，尺寸20*30*40cm','handBaggageDesc':'免费携带重量不超过10KG且体积不超过20*30*40cm的手提行李','refundRegular':'航班规定离站时间前7天（含）之前提出, 收取客票价60%的退票费;航班规定离站时间前7天至72小时（含）之内提出, 收取客票价70%的退票费;航班规定离站时间前72小时至4小时（含）之内提出, 收取客票价90%的退票费;航班规定离站时间前4小时之后提出, 不允许退票，仅限退还民航发展基金和燃油附加费。'},'canRefundChange':'可退可改','connectRuleText':'中转联程机票退改规则说明:联程客票中包含的所有航段同时办理退票的,按照各航段对应舱位的退票规则办理;联程客票仅部分航段退票的，仅退换该航段实际收取的相应税费。','handBaggage':'手提行李10kg','infRefundOrChangeRuleText':'持婴儿票的旅客要求变更、退票，均免收手续费','information':'表格内退票手续费是以当前时间进行客票变更而计算出的结果，最终手续费如有偏差，以实际退票时间与相应客规计算为准。;同等舱位变更后退票，变更手续费不予退还，以提出退票的时间和变更后的航班时间计算退票手续费。;升舱后退票，变更手续费不予退还，升舱部分，以提出退票时间和新客票的计飞时间对比，按升舱后的舱位退票费率计算退票手续费；升舱前客票部分，以原客票换开时间和原客票计飞时间对比，按变更前舱位退票费率计算退票手续费。','redPaperRuleText':'','refundOrChangeTicketRule':{'adtRefundOrChangeTicketFeeList':[{'changeFree':'¥259/人','description':'航班规定离站时间前7天（含）之前提出','endorseRule':'不予签转','refundFree':'¥311/人','timeType':'-8760--168'},{'changeFree':'¥311/人','description':'航班规定离站时间前7天至72小时（含）之内提出','endorseRule':'不予签转','refundFree':'¥363/人','timeType':'-168--72'},{'changeFree':'¥414/人','description':'航班规定离站时间前72小时至4小时（含）之内提出','endorseRule':'不予签转','refundFree':'¥466/人','timeType':'-72--4'},{'changeFree':'¥466/人','description':'航班规定离站时间前4小时之后提出','endorseRule':'不予签转','refundFree':'¥518/人','timeType':'-4-8760'}],'adtRefundOrChangeTicketFeeListSize':4,'chdRefundOrChangeTicketFeeList':[{'changeFree':'¥260/人','description':' 航班规定离站时间前7天（含）之前提出','endorseRule':'不予签转','refundFree':'¥312/人','timeType':'-8760--168'},{'changeFree':'¥312/人','description':' 航班规定离站时间前7天至72小时（含）之内提出','endorseRule':'不予签转','refundFree':'¥364/人','timeType':'-168--72'},{'changeFree':'¥416/人','description':' 航班规定离站时间前72小时至4小时（含）之内提出','endorseRule':'不予签转','refundFree':'¥468/人','timeType':'-72--4'},{'changeFree':'¥468/人','description':' 航班规定离站时间前4小时之后提出','endorseRule':'不予签转','refundFree':'¥520/人','timeType':'-4-8760'}],'chdRefundOrChangeTicketFeeListSize':4,'gmjcRefundOrChangeTicketFeeListSize':0,'infRefundOrChangeTicketFeeListSize':0},'sendRedAmount':''},'canChooseSeat':'false','carInfoSize':0,'depDate':'2019-09-01','depTime':'07:50','dstAirPort':{'code':'SHA','name':'上海虹桥','terminal':'T2'},'flightNo':'KN5737','orgAirPort':{'code':'NAY','name':'北京南苑','terminal':'--'},'passengers':[{'countryTypeCode':'CN','details':[{'amount':'518','status':'已出票','statusTypeCode':'TICKED','ticketNo':'822-2370017278'}],'detailsSize':1,'idNumber':'3214234355555','idTypeCode':'ID','name':'军阀测试','passType':'ADT','phoneNumber':'17602888888'},{'countryTypeCode':'CN','details':[{'amount':'520','status':'已出票','statusTypeCode':'TICKED','ticketNo':'822-2370017280'}],'detailsSize':1,'idNumber':'123234345679','idTypeCode':'ID','name':'小儿童测试','passType':'CHD','phoneNumber':'17602666666'},{'countryTypeCode':'CN','details':[{'amount':'150','status':'已出票','statusTypeCode':'TICKED','ticketNo':'822-2370017279'}],'detailsSize':1,'idNumber':'1253613475677','idTypeCode':'ID','name':'小婴儿测试','passType':'INF','phoneNumber':'17602777777'}],'passengersSize':3,'stopCity':'直达'}],'goItinerarysSize':1,'goodsName':'机票','groupCode':'AIR','rtItinerarysSize':0,'taxFeeTotals':{'ADT':{'passAmount':'1','passType':'ADT','taxFee':[{'description':'民航基金','price':'50','quantity':'1','sortNum':1,'taxFeeType':'CN'},{'description':'燃油','price':'0','quantity':'1','sortNum':2,'taxFeeType':'YQ'}],'taxFeeSize':2},'CHD':{'passAmount':'1','passType':'CHD','taxFee':[{'description':'民航基金','price':'0','quantity':'1','sortNum':1,'taxFeeType':'CN'},{'description':'燃油','price':'0','quantity':'1','sortNum':2,'taxFeeType':'YQ'}],'taxFeeSize':2},'INF':{'passAmount':'1','passType':'INF','taxFee':[{'description':'民航基金','price':'0','quantity':'1','sortNum':1,'taxFeeType':'CN'},{'description':'燃油','price':'0','quantity':'1','sortNum':2,'taxFeeType':'YQ'}],'taxFeeSize':2}},'taxFeeTotalsSize':3},'BAGGAGE':{'count':'2','goItinerarys':[{'aircraftType':'73U','arrDate':'2019-09-01','arrTime':'09:50','bookClass':'J','canChooseSeat':'false','carInfoSize':0,'depDate':'2019-09-01','depTime':'07:50','dstAirPort':{'code':'SHA','name':'上海虹桥','terminal':'T2'},'flightNo':'KN5737','orgAirPort':{'code':'NAY','name':'北京南苑','terminal':'--'},'passengers':[{'countryTypeCode':'CN','details':[{'amount':'320','ancillaryCode':'BAG40KG','name':'托运行李40KG','quantity':'1','status':'已预订','statusTypeCode':'TICKED','unitId':'129532'}],'detailsSize':1,'idNumber':'3214234355555','idTypeCode':'ID','name':'军阀测试','passType':'ADT','phoneNumber':'17602888888'},{'countryTypeCode':'CN','details':[{'amount':'200','ancillaryCode':'BAG25KG','name':'托运行李25KG','quantity':'1','status':'已预订','statusTypeCode':'TICKED','unitId':'129538'}],'detailsSize':1,'idNumber':'123234345679','idTypeCode':'ID','name':'小儿童测试','passType':'CHD','phoneNumber':'17602666666'},{'countryTypeCode':'CN','detailsSize':0,'idNumber':'1253613475677','idTypeCode':'ID','name':'小婴儿测试','passType':'INF','phoneNumber':'17602777777'}],'passengersSize':3,'stopCity':'直达'}],'goItinerarysSize':1,'goodsName':'行李','groupCode':'BAGGAGE','rtItinerarysSize':0,'taxFeeTotalsSize':0},'INSURANCE':{'count':'4','goItinerarys':[{'aircraftType':'73U','arrDate':'2019-09-01','arrTime':'09:50','bookClass':'J','canChooseSeat':'false','carInfoSize':0,'depDate':'2019-09-01','depTime':'07:50','dstAirPort':{'code':'SHA','name':'上海虹桥','terminal':'T2'},'flightNo':'KN5737','orgAirPort':{'code':'NAY','name':'北京南苑','terminal':'--'},'passengers':[{'countryTypeCode':'CN','details':[{'airStatus':'已出票','amount':'30','ancillaryCode':'AUISAVAI','name':'航空意外险','quantity':'1','status':'购保失败','statusTypeCode':'TICKED','ticketNo':'ERROR','unitId':'129533'},{'airStatus':'已出票','amount':'30','ancillaryCode':'AUISAVRI','name':'航空退票险','quantity':'1','status':'购保成功','statusTypeCode':'TICKED','ticketNo':'AJINJQT59819EAM76M50','unitId':'129535'},{'airStatus':'已出票','amount':'20','ancillaryCode':'AUISAVDI','name':'航班延误险','quantity':'1','status':'购保失败','statusTypeCode':'TICKED','ticketNo':'ERROR','unitId':'129536'}],'detailsSize':3,'idNumber':'3214234355555','idTypeCode':'ID','name':'军阀测试','passType':'ADT','phoneNumber':'17602888888'},{'countryTypeCode':'CN','details':[{'airStatus':'已出票','amount':'30','ancillaryCode':'AUISAVAI','name':'航空意外险','quantity':'1','status':'购保失败','statusTypeCode':'TICKED','ticketNo':'ERROR','unitId':'129534'}],'detailsSize':1,'idNumber':'123234345679','idTypeCode':'ID','name':'小儿童测试','passType':'CHD','phoneNumber':'17602666666'},{'countryTypeCode':'CN','detailsSize':0,'idNumber':'1253613475677','idTypeCode':'ID','name':'小婴儿测试','passType':'INF','phoneNumber':'17602777777'}],'passengersSize':3,'stopCity':'直达'}],'goItinerarysSize':1,'goodsName':'保险','groupCode':'INSURANCE','rtItinerarysSize':0,'taxFeeTotalsSize':0},'MEAL':{'count':'1','goItinerarys':[{'aircraftType':'73U','arrDate':'2019-09-01','arrTime':'09:50','bookClass':'J','canChooseSeat':'false','carInfoSize':0,'depDate':'2019-09-01','depTime':'07:50','dstAirPort':{'code':'SHA','name':'上海虹桥','terminal':'T2'},'flightNo':'KN5737','orgAirPort':{'code':'NAY','name':'北京南苑','terminal':'--'},'passengers':[{'countryTypeCode':'CN','details':[{'amount':'12','ancillaryCode':'TC1M','name':'黄焖鸡米饭套餐','quantity':'1','status':'已预订','statusTypeCode':'TICKED','unitId':'129537'}],'detailsSize':1,'idNumber':'3214234355555','idTypeCode':'ID','name':'军阀测试','passType':'ADT','phoneNumber':'17602888888'},{'countryTypeCode':'CN','detailsSize':0,'idNumber':'123234345679','idTypeCode':'ID','name':'小儿童测试','passType':'CHD','phoneNumber':'17602666666'},{'countryTypeCode':'CN','detailsSize':0,'idNumber':'1253613475677','idTypeCode':'ID','name':'小婴儿测试','passType':'INF','phoneNumber':'17602777777'}],'passengersSize':3,'stopCity':'直达'}],'goItinerarysSize':1,'goodsName':'餐食','groupCode':'MEAL','rtItinerarysSize':0,'taxFeeTotalsSize':0}},'componentsSize':4,'contact':{'name':'朱泽洋','telNumber':'17602656463'},'iOrD':'D','isAnnualOrder':'false','isChangeOrder':false,'isGmjcOrder':false,'orderAmount':'1880','orderCreateTime':'2019-07-30 18:02:09','orderMode':'2','orderNo':'20J7V1BP6I25','orderStatus':'已出票','orderTypeCode':'NORMALFARE','payInfos':[{'bussinessCode':'H5','isPayForTicket':'true','payAmount':'1880','payType':'虚拟支付','paytime':'2019-07-30 18:04','transactionNo':'ATGJ7V1BPK669'}],'payInfosSize':1,'redAmount':'','statusTypeCode':'TICKED','tripType':'ONEWAY'}}
export const test1={
    'commonRes':{
        'isOk':true
    },
    'orderDetail':{
        'bussinessCode':'H5',
        'canBuyAncillary':'false',
        'canCancelSeat':'false',
        'canChange':'false',
        'canChooseSeat':'false',
        'canRefund':'false',
        'components':{
            'AIR':{
                'count':'12',
                'goItinerarys':[
                    {
                        'aircraftType':'73V',
                        'arrDate':'2019-08-23',
                        'arrTime':'09:55',
                        'bookClass':'R',
                        'brandInfo':{
                            'brandCode':'CYY',
                            'brandName':'大众游',
                            'brandPolicy':{
                                'changeRegular':'航班规定离站时间前168小时（含）之前提出,收取客票价20%的变更费; 航班规定离站时间前168小时至72小时（含）之内提出,收取客票价30%的变更费; 航班规定离站时间前72小时至24小时（含）之内提出,收取客票价40%的变更费; 航班规定离站时间前24小时之后提出,收取客票价50%的变更费。',
                                'checkBaggageDesc':'无免费托运行李额',
                                'handBaggage':'10KG，尺寸20*30*40cm',
                                'handBaggageDesc':'免费携带重量不超过10kg且体积不超过20*30*40cm的手提行李',
                                'refundRegular':'航班规定离站时间前168小时（含）之前提出, 收取客票价30%的退票费;航班规定离站时间前168小时至72小时（含）之内提出, 收取客票价40%的退票费;航班规定离站时间前72小时至24小时（含）之内提出, 收取客票价50%的退票费;航班规定离站时间前24小时之后提出, 不允许退票，仅限退还已经代为实际征收的民航发展基金和燃油附加费。'
                            },
                            'canRefundChange':'可退可改',
                            'connectRuleText':'中转联程机票退改规则说明:联程客票中包含的所有航段同时办理退票的,按照各航段对应舱位的退票规则办理;联程客票仅部分航段退票的，仅退换该航段实际收取的相应税费。',
                            'handBaggage':'手提行李10kg',
                            'infRefundOrChangeRuleText':'持婴儿票的旅客要求变更、退票，均免收手续费',
                            'information':'表格内退票手续费是以当前时间进行客票变更而计算出的结果，最终手续费如有偏差，以实际退票时间与相应客规计算为准。;同等舱位变更后退票，变更手续费不予退还，以提出退票的时间和变更后的航班时间计算退票手续费。;升舱后退票，变更手续费不予退还，升舱部分，以提出退票时间和新客票的计飞时间对比，按升舱后的舱位退票费率计算退票手续费；升舱前客票部分，以原客票换开时间和原客票计飞时间对比，按变更前舱位退票费率计算退票手续费。',
                            'redPaperRuleText':'大众游产品成行后赠送票价1%的红包',
                            'refundOrChangeTicketRule':{
                                'adtRefundOrChangeTicketFeeList':[
                                    {
                                        'changeFree':'¥90/人',
                                        'description':'航班规定离站时间前168小时（含）之前提出',
                                        'endorseRule':'不予签转',
                                        'refundFree':'¥134/人',
                                        'timeType':'-8760--168'
                                    },
                                    {
                                        'changeFree':'¥134/人',
                                        'description':'航班规定离站时间前168小时至72小时（含）之内提出',
                                        'endorseRule':'不予签转',
                                        'refundFree':'¥179/人',
                                        'timeType':'-168--72'
                                    },
                                    {
                                        'changeFree':'¥179/人',
                                        'description':'航班规定离站时间前72小时至24小时（含）之内提出',
                                        'endorseRule':'不予签转',
                                        'refundFree':'¥224/人',
                                        'timeType':'-72--24'
                                    },
                                    {
                                        'changeFree':'¥224/人',
                                        'description':'航班规定离站时间前24小时之后提出',
                                        'endorseRule':'不予签转',
                                        'refundFree':'¥448/人',
                                        'timeType':'-24-8760'
                                    }
                                ],
                                'adtRefundOrChangeTicketFeeListSize':4,
                                'chdRefundOrChangeTicketFeeList':[
                                    {
                                        'changeFree':'¥88/人',
                                        'description':'航班规定离站时间前168小时（含）之前提出',
                                        'endorseRule':'不予签转',
                                        'refundFree':'¥132/人',
                                        'timeType':'-8760--168'
                                    },
                                    {
                                        'changeFree':'¥132/人',
                                        'description':'航班规定离站时间前168小时至72小时（含）之内提出',
                                        'endorseRule':'不予签转',
                                        'refundFree':'¥176/人',
                                        'timeType':'-168--72'
                                    },
                                    {
                                        'changeFree':'¥176/人',
                                        'description':'航班规定离站时间前72小时至24小时（含）之内提出',
                                        'endorseRule':'不予签转',
                                        'refundFree':'¥220/人',
                                        'timeType':'-72--24'
                                    },
                                    {
                                        'changeFree':'¥220/人',
                                        'description':'航班规定离站时间前24小时之后提出',
                                        'endorseRule':'不予签转',
                                        'refundFree':'¥440/人',
                                        'timeType':'-24-8760'
                                    }
                                ],
                                'chdRefundOrChangeTicketFeeListSize':4,
                                'gmjcRefundOrChangeTicketFeeListSize':0,
                                'infRefundOrChangeTicketFeeListSize':0
                            },
                            'sendRedAmount':'成行后送15元红包'
                        },
                        'canChooseSeat':'false',
                        'carInfoSize':0,
                        'depDate':'2019-08-23',
                        'depTime':'08:50',
                        'dstAirPort':{
                            'code':'NAY',
                            'descr':'北京南苑',
                            'name':'北京南苑',
                            'terminal':'--'
                        },
                        'flightNo':'KN2922',
                        'orgAirPort':{
                            'code':'CIF',
                            'descr':'赤峰',
                            'name':'赤峰',
                            'terminal':'--'
                        },
                        'passengers':[
                            {
                                'countryTypeCode':'CN',
                                'details':[
                                    {
                                        'amount':'448',
                                        'status':'--',
                                        'statusTypeCode':'BOOKED'
                                    }
                                ],
                                'detailsSize':1,
                                'idNumber':'132312334987324',
                                'idTypeCode':'ID',
                                'name':'一样测试',
                                'passType':'ADT',
                                'phoneNumber':'13716827113'
                            },
                            {
                                'countryTypeCode':'CN',
                                'details':[
                                    {
                                        'amount':'440',
                                        'status':'--',
                                        'statusTypeCode':'BOOKED'
                                    }
                                ],
                                'detailsSize':1,
                                'idNumber':'132312334987325',
                                'idTypeCode':'ID',
                                'name':'小儿童测试',
                                'passType':'CHD',
                                'phoneNumber':'17602655555'
                            },
                            {
                                'countryTypeCode':'CN',
                                'details':[
                                    {
                                        'amount':'448',
                                        'status':'--',
                                        'statusTypeCode':'BOOKED'
                                    }
                                ],
                                'detailsSize':1,
                                'idNumber':'132312334987326',
                                'idTypeCode':'ID',
                                'name':'马天利测试',
                                'passType':'ADT',
                                'phoneNumber':'16600987345'
                            }
                        ],
                        'passengersSize':3,
                        'stopCity':'直达'
                    },
                    {
                        'aircraftType':'73V',
                        'arrDate':'2019-08-23',
                        'arrTime':'17:40',
                        'bookClass':'B',
                        'brandInfo':{
                            'brandCode':'CYY',
                            'brandName':'大众游',
                            'brandPolicy':{
                                'changeRegular':'航班规定离站时间前168小时（含）之前提出,收取客票价20%的变更费; 航班规定离站时间前168小时至72小时（含）之内提出,收取客票价30%的变更费; 航班规定离站时间前72小时至24小时（含）之内提出,收取客票价40%的变更费; 航班规定离站时间前24小时之后提出,收取客票价50%的变更费。',
                                'checkBaggage':'20KG，尺寸40*60*100cm',
                                'checkBaggageDesc':'免费托运重量不超过20kg且体积不超过40*60*100cm的托运行李',
                                'handBaggage':'10KG，尺寸20*30*40cm',
                                'handBaggageDesc':'免费携带重量不超过10kg且体积不超过20*30*40cm的手提行李',
                                'refundRegular':'航班规定离站时间前168小时（含）之前提出, 收取客票价30%的退票费;航班规定离站时间前168小时至72小时（含）之内提出, 收取客票价40%的退票费;航班规定离站时间前72小时至24小时（含）之内提出, 收取客票价50%的退票费;航班规定离站时间前24小时之后提出, 不允许退票，仅限退还已经代为实际征收的民航发展基金和燃油附加费。'
                            },
                            'canRefundChange':'可退可改',
                            'checkBaggage':'托运行李20kg',
                            'connectRuleText':'中转联程机票退改规则说明:联程客票中包含的所有航段同时办理退票的,按照各航段对应舱位的退票规则办理;联程客票仅部分航段退票的，仅退换该航段实际收取的相应税费。',
                            'handBaggage':'手提行李10kg',
                            'infRefundOrChangeRuleText':'持婴儿票的旅客要求变更、退票，均免收手续费',
                            'information':'表格内退票手续费是以当前时间进行客票变更而计算出的结果，最终手续费如有偏差，以实际退票时间与相应客规计算为准。;同等舱位变更后退票，变更手续费不予退还，以提出退票的时间和变更后的航班时间计算退票手续费。;升舱后退票，变更手续费不予退还，升舱部分，以提出退票时间和新客票的计飞时间对比，按升舱后的舱位退票费率计算退票手续费；升舱前客票部分，以原客票换开时间和原客票计飞时间对比，按变更前舱位退票费率计算退票手续费。',
                            'redPaperRuleText':'大众游产品成行后赠送票价3%的红包',
                            'refundOrChangeTicketRule':{
                                'adtRefundOrChangeTicketFeeList':[
                                    {
                                        'changeFree':'¥296/人',
                                        'description':'航班规定离站时间前168小时（含）之前提出',
                                        'endorseRule':'不予签转',
                                        'refundFree':'¥443/人',
                                        'timeType':'-8760--168'
                                    },
                                    {
                                        'changeFree':'¥443/人',
                                        'description':'航班规定离站时间前168小时至72小时（含）之内提出',
                                        'endorseRule':'不予签转',
                                        'refundFree':'¥591/人',
                                        'timeType':'-168--72'
                                    },
                                    {
                                        'changeFree':'¥591/人',
                                        'description':'航班规定离站时间前72小时至24小时（含）之内提出',
                                        'endorseRule':'不予签转',
                                        'refundFree':'¥739/人',
                                        'timeType':'-72--24'
                                    },
                                    {
                                        'changeFree':'¥739/人',
                                        'description':'航班规定离站时间前24小时之后提出',
                                        'endorseRule':'不予签转',
                                        'refundFree':'¥1478/人',
                                        'timeType':'-24-8760'
                                    }
                                ],
                                'adtRefundOrChangeTicketFeeListSize':4,
                                'chdRefundOrChangeTicketFeeList':[
                                    {
                                        'changeFree':'¥148/人',
                                        'description':'航班规定离站时间前168小时（含）之前提出',
                                        'endorseRule':'不予签转',
                                        'refundFree':'¥222/人',
                                        'timeType':'-8760--168'
                                    },
                                    {
                                        'changeFree':'¥222/人',
                                        'description':'航班规定离站时间前168小时至72小时（含）之内提出',
                                        'endorseRule':'不予签转',
                                        'refundFree':'¥296/人',
                                        'timeType':'-168--72'
                                    },
                                    {
                                        'changeFree':'¥296/人',
                                        'description':'航班规定离站时间前72小时至24小时（含）之内提出',
                                        'endorseRule':'不予签转',
                                        'refundFree':'¥370/人',
                                        'timeType':'-72--24'
                                    },
                                    {
                                        'changeFree':'¥370/人',
                                        'description':' 航班规定离站时间前24小时之后提出',
                                        'endorseRule':'不予签转',
                                        'refundFree':'¥740/人',
                                        'timeType':'-24-8760'
                                    }
                                ],
                                'chdRefundOrChangeTicketFeeListSize':4,
                                'gmjcRefundOrChangeTicketFeeListSize':0,
                                'infRefundOrChangeTicketFeeListSize':0
                            },
                            'sendRedAmount':'成行后送113元红包'
                        },
                        'canChooseSeat':'false',
                        'carInfoSize':0,
                        'depDate':'2019-08-23',
                        'depTime':'15:40',
                        'dstAirPort':{
                            'code':'SHA',
                            'descr':'上海虹桥',
                            'name':'上海虹桥',
                            'terminal':'T2'
                        },
                        'flightNo':'KN5955',
                        'orgAirPort':{
                            'code':'NAY',
                            'descr':'北京南苑',
                            'name':'北京南苑',
                            'terminal':'--'
                        },
                        'passengers':[
                            {
                                'countryTypeCode':'CN',
                                'details':[
                                    {
                                        'amount':'1478',
                                        'status':'--',
                                        'statusTypeCode':'BOOKED'
                                    }
                                ],
                                'detailsSize':1,
                                'idNumber':'132312334987324',
                                'idTypeCode':'ID',
                                'name':'一样测试',
                                'passType':'ADT',
                                'phoneNumber':'13716827113'
                            },
                            {
                                'countryTypeCode':'CN',
                                'details':[
                                    {
                                        'amount':'740',
                                        'status':'--',
                                        'statusTypeCode':'BOOKED'
                                    }
                                ],
                                'detailsSize':1,
                                'idNumber':'132312334987325',
                                'idTypeCode':'ID',
                                'name':'小儿童测试',
                                'passType':'CHD',
                                'phoneNumber':'17602655555'
                            },
                            {
                                'countryTypeCode':'CN',
                                'details':[
                                    {
                                        'amount':'1478',
                                        'status':'--',
                                        'statusTypeCode':'BOOKED'
                                    }
                                ],
                                'detailsSize':1,
                                'idNumber':'132312334987326',
                                'idTypeCode':'ID',
                                'name':'马天利测试',
                                'passType':'ADT',
                                'phoneNumber':'16600987345'
                            }
                        ],
                        'passengersSize':3,
                        'stopCity':'直达'
                    }
                ],
                'goItinerarysSize':2,
                'goodsName':'机票',
                'groupCode':'AIR',
                'rtItinerarys':[
                    {
                        'aircraftType':'73V',
                        'arrDate':'2019-08-25',
                        'arrTime':'21:00',
                        'bookClass':'L',
                        'brandInfo':{
                            'brandCode':'CYY',
                            'brandName':'大众游',
                            'brandPolicy':{
                                'changeRegular':'航班规定离站时间前168小时（含）之前提出,收取客票价20%的变更费; 航班规定离站时间前168小时至72小时（含）之内提出,收取客票价30%的变更费; 航班规定离站时间前72小时至24小时（含）之内提出,收取客票价40%的变更费; 航班规定离站时间前24小时之后提出,收取客票价50%的变更费。',
                                'checkBaggageDesc':'无免费托运行李额',
                                'handBaggage':'10KG，尺寸20*30*40cm',
                                'handBaggageDesc':'免费携带重量不超过10kg且体积不超过20*30*40cm的手提行李',
                                'refundRegular':'航班规定离站时间前168小时（含）之前提出, 收取客票价30%的退票费;航班规定离站时间前168小时至72小时（含）之内提出, 收取客票价40%的退票费;航班规定离站时间前72小时至24小时（含）之内提出, 收取客票价50%的退票费;航班规定离站时间前24小时之后提出, 不允许退票，仅限退还已经代为实际征收的民航发展基金和燃油附加费。'
                            },
                            'canRefundChange':'可退可改',
                            'connectRuleText':'中转联程机票退改规则说明:联程客票中包含的所有航段同时办理退票的,按照各航段对应舱位的退票规则办理;联程客票仅部分航段退票的，仅退换该航段实际收取的相应税费。',
                            'handBaggage':'手提行李10kg',
                            'infRefundOrChangeRuleText':'持婴儿票的旅客要求变更、退票，均免收手续费',
                            'information':'表格内退票手续费是以当前时间进行客票变更而计算出的结果，最终手续费如有偏差，以实际退票时间与相应客规计算为准。;同等舱位变更后退票，变更手续费不予退还，以提出退票的时间和变更后的航班时间计算退票手续费。;升舱后退票，变更手续费不予退还，升舱部分，以提出退票时间和新客票的计飞时间对比，按升舱后的舱位退票费率计算退票手续费；升舱前客票部分，以原客票换开时间和原客票计飞时间对比，按变更前舱位退票费率计算退票手续费。',
                            'redPaperRuleText':'大众游产品成行后赠送票价1%的红包',
                            'refundOrChangeTicketRule':{
                                'adtRefundOrChangeTicketFeeList':[
                                    {
                                        'changeFree':'¥194/人',
                                        'description':'航班规定离站时间前168小时（含）之前提出',
                                        'endorseRule':'不予签转',
                                        'refundFree':'¥290/人',
                                        'timeType':'-8760--168'
                                    },
                                    {
                                        'changeFree':'¥290/人',
                                        'description':'航班规定离站时间前168小时至72小时（含）之内提出',
                                        'endorseRule':'不予签转',
                                        'refundFree':'¥387/人',
                                        'timeType':'-168--72'
                                    },
                                    {
                                        'changeFree':'¥387/人',
                                        'description':'航班规定离站时间前72小时至24小时（含）之内提出',
                                        'endorseRule':'不予签转',
                                        'refundFree':'¥484/人',
                                        'timeType':'-72--24'
                                    },
                                    {
                                        'changeFree':'¥484/人',
                                        'description':'航班规定离站时间前24小时之后提出',
                                        'endorseRule':'不予签转',
                                        'refundFree':'¥968/人',
                                        'timeType':'-24-8760'
                                    }
                                ],
                                'adtRefundOrChangeTicketFeeListSize':4,
                                'chdRefundOrChangeTicketFeeList':[
                                    {
                                        'changeFree':'¥148/人',
                                        'description':'航班规定离站时间前168小时（含）之前提出',
                                        'endorseRule':'不予签转',
                                        'refundFree':'¥222/人',
                                        'timeType':'-8760--168'
                                    },
                                    {
                                        'changeFree':'¥222/人',
                                        'description':'航班规定离站时间前168小时至72小时（含）之内提出',
                                        'endorseRule':'不予签转',
                                        'refundFree':'¥296/人',
                                        'timeType':'-168--72'
                                    },
                                    {
                                        'changeFree':'¥296/人',
                                        'description':'航班规定离站时间前72小时至24小时（含）之内提出',
                                        'endorseRule':'不予签转',
                                        'refundFree':'¥370/人',
                                        'timeType':'-72--24'
                                    },
                                    {
                                        'changeFree':'¥370/人',
                                        'description':'航班规定离站时间前24小时之后提出',
                                        'endorseRule':'不予签转',
                                        'refundFree':'¥740/人',
                                        'timeType':'-24-8760'
                                    }
                                ],
                                'chdRefundOrChangeTicketFeeListSize':4,
                                'gmjcRefundOrChangeTicketFeeListSize':0,
                                'infRefundOrChangeTicketFeeListSize':0
                            },
                            'sendRedAmount':'成行后送28元红包'
                        },
                        'canChooseSeat':'false',
                        'carInfoSize':0,
                        'depDate':'2019-08-25',
                        'depTime':'18:40',
                        'dstAirPort':{
                            'code':'NAY',
                            'descr':'北京南苑',
                            'name':'北京南苑',
                            'terminal':'--'
                        },
                        'flightNo':'KN5956',
                        'orgAirPort':{
                            'code':'SHA',
                            'descr':'上海虹桥',
                            'name':'上海虹桥',
                            'terminal':'T2'
                        },
                        'passengers':[
                            {
                                'countryTypeCode':'CN',
                                'details':[
                                    {
                                        'amount':'968',
                                        'status':'--',
                                        'statusTypeCode':'BOOKED'
                                    }
                                ],
                                'detailsSize':1,
                                'idNumber':'132312334987324',
                                'idTypeCode':'ID',
                                'name':'一样测试',
                                'passType':'ADT',
                                'phoneNumber':'13716827113'
                            },
                            {
                                'countryTypeCode':'CN',
                                'details':[
                                    {
                                        'amount':'740',
                                        'status':'--',
                                        'statusTypeCode':'BOOKED'
                                    }
                                ],
                                'detailsSize':1,
                                'idNumber':'132312334987325',
                                'idTypeCode':'ID',
                                'name':'小儿童测试',
                                'passType':'CHD',
                                'phoneNumber':'17602655555'
                            },
                            {
                                'countryTypeCode':'CN',
                                'details':[
                                    {
                                        'amount':'968',
                                        'status':'--',
                                        'statusTypeCode':'BOOKED'
                                    }
                                ],
                                'detailsSize':1,
                                'idNumber':'132312334987326',
                                'idTypeCode':'ID',
                                'name':'马天利测试',
                                'passType':'ADT',
                                'phoneNumber':'16600987345'
                            }
                        ],
                        'passengersSize':3,
                        'stopCity':'直达'
                    },
                    {
                        'aircraftType':'73V',
                        'arrDate':'2019-08-26',
                        'arrTime':'08:05',
                        'bookClass':'R',
                        'brandInfo':{
                            'brandCode':'CYY',
                            'brandName':'大众游',
                            'brandPolicy':{
                                'changeRegular':'航班规定离站时间前168小时（含）之前提出,收取客票价20%的变更费; 航班规定离站时间前168小时至72小时（含）之内提出,收取客票价30%的变更费; 航班规定离站时间前72小时至24小时（含）之内提出,收取客票价40%的变更费; 航班规定离站时间前24小时之后提出,收取客票价50%的变更费。',
                                'checkBaggageDesc':'无免费托运行李额',
                                'handBaggage':'10KG，尺寸20*30*40cm',
                                'handBaggageDesc':'免费携带重量不超过10kg且体积不超过20*30*40cm的手提行李',
                                'refundRegular':'航班规定离站时间前168小时（含）之前提出, 收取客票价30%的退票费;航班规定离站时间前168小时至72小时（含）之内提出, 收取客票价40%的退票费;航班规定离站时间前72小时至24小时（含）之内提出, 收取客票价50%的退票费;航班规定离站时间前24小时之后提出, 不允许退票，仅限退还已经代为实际征收的民航发展基金和燃油附加费。'
                            },
                            'canRefundChange':'可退可改',
                            'connectRuleText':'中转联程机票退改规则说明:联程客票中包含的所有航段同时办理退票的,按照各航段对应舱位的退票规则办理;联程客票仅部分航段退票的，仅退换该航段实际收取的相应税费。',
                            'handBaggage':'手提行李10kg',
                            'infRefundOrChangeRuleText':'持婴儿票的旅客要求变更、退票，均免收手续费',
                            'information':'表格内退票手续费是以当前时间进行客票变更而计算出的结果，最终手续费如有偏差，以实际退票时间与相应客规计算为准。;同等舱位变更后退票，变更手续费不予退还，以提出退票的时间和变更后的航班时间计算退票手续费。;升舱后退票，变更手续费不予退还，升舱部分，以提出退票时间和新客票的计飞时间对比，按升舱后的舱位退票费率计算退票手续费；升舱前客票部分，以原客票换开时间和原客票计飞时间对比，按变更前舱位退票费率计算退票手续费。',
                            'redPaperRuleText':'大众游产品成行后赠送票价1%的红包',
                            'refundOrChangeTicketRule':{
                                'adtRefundOrChangeTicketFeeList':[
                                    {
                                        'changeFree':'¥90/人',
                                        'description':'航班规定离站时间前168小时（含）之前提出',
                                        'endorseRule':'不予签转',
                                        'refundFree':'¥134/人',
                                        'timeType':'-8760--168'
                                    },
                                    {
                                        'changeFree':'¥134/人',
                                        'description':'航班规定离站时间前168小时至72小时（含）之内提出',
                                        'endorseRule':'不予签转',
                                        'refundFree':'¥179/人',
                                        'timeType':'-168--72'
                                    },
                                    {
                                        'changeFree':'¥179/人',
                                        'description':'航班规定离站时间前72小时至24小时（含）之内提出',
                                        'endorseRule':'不予签转',
                                        'refundFree':'¥224/人',
                                        'timeType':'-72--24'
                                    },
                                    {
                                        'changeFree':'¥224/人',
                                        'description':'航班规定离站时间前24小时之后提出',
                                        'endorseRule':'不予签转',
                                        'refundFree':'¥448/人',
                                        'timeType':'-24-8760'
                                    }
                                ],
                                'adtRefundOrChangeTicketFeeListSize':4,
                                'chdRefundOrChangeTicketFeeList':[
                                    {
                                        'changeFree':'¥88/人',
                                        'description':'航班规定离站时间前168小时（含）之前提出',
                                        'endorseRule':'不予签转',
                                        'refundFree':'¥132/人',
                                        'timeType':'-8760--168'
                                    },
                                    {
                                        'changeFree':'¥132/人',
                                        'description':'航班规定离站时间前168小时至72小时（含）之内提出',
                                        'endorseRule':'不予签转',
                                        'refundFree':'¥176/人',
                                        'timeType':'-168--72'
                                    },
                                    {
                                        'changeFree':'¥176/人',
                                        'description':'航班规定离站时间前72小时至24小时（含）之内提出',
                                        'endorseRule':'不予签转',
                                        'refundFree':'¥220/人',
                                        'timeType':'-72--24'
                                    },
                                    {
                                        'changeFree':'¥220/人',
                                        'description':'航班规定离站时间前24小时之后提出',
                                        'endorseRule':'不予签转',
                                        'refundFree':'¥440/人',
                                        'timeType':'-24-8760'
                                    }
                                ],
                                'chdRefundOrChangeTicketFeeListSize':4,
                                'gmjcRefundOrChangeTicketFeeListSize':0,
                                'infRefundOrChangeTicketFeeListSize':0
                            },
                            'sendRedAmount':'成行后送15元红包'
                        },
                        'canChooseSeat':'false',
                        'carInfoSize':0,
                        'depDate':'2019-08-26',
                        'depTime':'07:00',
                        'dstAirPort':{
                            'code':'CIF',
                            'descr':'赤峰',
                            'name':'赤峰',
                            'terminal':'--'
                        },
                        'flightNo':'KN2921',
                        'orgAirPort':{
                            'code':'NAY',
                            'descr':'北京南苑',
                            'name':'北京南苑',
                            'terminal':'--'
                        },
                        'passengers':[
                            {
                                'countryTypeCode':'CN',
                                'details':[
                                    {
                                        'amount':'448',
                                        'status':'--',
                                        'statusTypeCode':'BOOKED'
                                    }
                                ],
                                'detailsSize':1,
                                'idNumber':'132312334987324',
                                'idTypeCode':'ID',
                                'name':'一样测试',
                                'passType':'ADT',
                                'phoneNumber':'13716827113'
                            },
                            {
                                'countryTypeCode':'CN',
                                'details':[
                                    {
                                        'amount':'440',
                                        'status':'--',
                                        'statusTypeCode':'BOOKED'
                                    }
                                ],
                                'detailsSize':1,
                                'idNumber':'132312334987325',
                                'idTypeCode':'ID',
                                'name':'小儿童测试',
                                'passType':'CHD',
                                'phoneNumber':'17602655555'
                            },
                            {
                                'countryTypeCode':'CN',
                                'details':[
                                    {
                                        'amount':'448',
                                        'status':'--',
                                        'statusTypeCode':'BOOKED'
                                    }
                                ],
                                'detailsSize':1,
                                'idNumber':'132312334987326',
                                'idTypeCode':'ID',
                                'name':'马天利测试',
                                'passType':'ADT',
                                'phoneNumber':'16600987345'
                            }
                        ],
                        'passengersSize':3,
                        'stopCity':'直达'
                    }
                ],
                'rtItinerarysSize':2,
                'taxFeeTotals':{
                    'ADT':{
                        'passAmount':'2',
                        'passType':'ADT',
                        'taxFee':[
                            {
                                'description':'民航基金',
                                'price':'50',
                                'quantity':'8',
                                'sortNum':1,
                                'taxFeeType':'CN'
                            },
                            {
                                'description':'燃油',
                                'price':'0',
                                'quantity':'8',
                                'sortNum':2,
                                'taxFeeType':'YQ'
                            }
                        ],
                        'taxFeeSize':2
                    },
                    'CHD':{
                        'passAmount':'1',
                        'passType':'CHD',
                        'taxFee':[
                            {
                                'description':'民航基金',
                                'price':'0',
                                'quantity':'4',
                                'sortNum':1,
                                'taxFeeType':'CN'
                            },
                            {
                                'description':'燃油',
                                'price':'0',
                                'quantity':'4',
                                'sortNum':2,
                                'taxFeeType':'YQ'
                            }
                        ],
                        'taxFeeSize':2
                    }
                },
                'taxFeeTotalsSize':2
            },
            'BAGGAGE':{
                'count':'9',
                'goItinerarys':[
                    {
                        'aircraftType':'73V',
                        'arrDate':'2019-08-23',
                        'arrTime':'09:55',
                        'bookClass':'R',
                        'canChooseSeat':'false',
                        'carInfoSize':0,
                        'depDate':'2019-08-23',
                        'depTime':'08:50',
                        'dstAirPort':{
                            'code':'NAY',
                            'descr':'北京南苑',
                            'name':'北京南苑',
                            'terminal':'--'
                        },
                        'flightNo':'KN2922',
                        'orgAirPort':{
                            'code':'CIF',
                            'descr':'赤峰',
                            'name':'赤峰',
                            'terminal':'--'
                        },
                        'passengers':[
                            {
                                'countryTypeCode':'CN',
                                'details':[
                                    {
                                        'amount':'23',
                                        'ancillaryCode':'BAG5KG',
                                        'name':'托运行李5KG',
                                        'quantity':'1',
                                        'status':'--',
                                        'statusTypeCode':'BOOKED',
                                        'unitId':'128240'
                                    }
                                ],
                                'detailsSize':1,
                                'idNumber':'132312334987324',
                                'idTypeCode':'ID',
                                'name':'一样测试',
                                'passType':'ADT',
                                'phoneNumber':'13716827113'
                            },
                            {
                                'countryTypeCode':'CN',
                                'details':[
                                    {
                                        'amount':'115',
                                        'ancillaryCode':'BAG25KG',
                                        'name':'托运行李25KG',
                                        'quantity':'1',
                                        'status':'--',
                                        'statusTypeCode':'BOOKED',
                                        'unitId':'128246'
                                    }
                                ],
                                'detailsSize':1,
                                'idNumber':'132312334987325',
                                'idTypeCode':'ID',
                                'name':'小儿童测试',
                                'passType':'CHD',
                                'phoneNumber':'17602655555'
                            },
                            {
                                'countryTypeCode':'CN',
                                'detailsSize':0,
                                'idNumber':'132312334987326',
                                'idTypeCode':'ID',
                                'name':'马天利测试',
                                'passType':'ADT',
                                'phoneNumber':'16600987345'
                            }
                        ],
                        'passengersSize':3,
                        'stopCity':'直达'
                    },
                    {
                        'aircraftType':'73V',
                        'arrDate':'2019-08-23',
                        'arrTime':'17:40',
                        'bookClass':'B',
                        'canChooseSeat':'false',
                        'carInfoSize':0,
                        'depDate':'2019-08-23',
                        'depTime':'15:40',
                        'dstAirPort':{
                            'code':'SHA',
                            'descr':'上海虹桥',
                            'name':'上海虹桥',
                            'terminal':'T2'
                        },
                        'flightNo':'KN5955',
                        'orgAirPort':{
                            'code':'NAY',
                            'descr':'北京南苑',
                            'name':'北京南苑',
                            'terminal':'--'
                        },
                        'passengers':[
                            {
                                'countryTypeCode':'CN',
                                'detailsSize':0,
                                'idNumber':'132312334987324',
                                'idTypeCode':'ID',
                                'name':'一样测试',
                                'passType':'ADT',
                                'phoneNumber':'13716827113'
                            },
                            {
                                'countryTypeCode':'CN',
                                'details':[
                                    {
                                        'amount':'135',
                                        'ancillaryCode':'BAG15KG',
                                        'name':'托运行李15KG',
                                        'quantity':'1',
                                        'status':'--',
                                        'statusTypeCode':'BOOKED',
                                        'unitId':'128244'
                                    }
                                ],
                                'detailsSize':1,
                                'idNumber':'132312334987325',
                                'idTypeCode':'ID',
                                'name':'小儿童测试',
                                'passType':'CHD',
                                'phoneNumber':'17602655555'
                            },
                            {
                                'countryTypeCode':'CN',
                                'details':[
                                    {
                                        'amount':'315',
                                        'ancillaryCode':'BAG35KG',
                                        'name':'托运行李35KG',
                                        'quantity':'1',
                                        'status':'--',
                                        'statusTypeCode':'BOOKED',
                                        'unitId':'128248'
                                    }
                                ],
                                'detailsSize':1,
                                'idNumber':'132312334987326',
                                'idTypeCode':'ID',
                                'name':'马天利测试',
                                'passType':'ADT',
                                'phoneNumber':'16600987345'
                            }
                        ],
                        'passengersSize':3,
                        'stopCity':'直达'
                    }
                ],
                'goItinerarysSize':2,
                'goodsName':'行李',
                'groupCode':'BAGGAGE',
                'rtItinerarys':[
                    {
                        'aircraftType':'73V',
                        'arrDate':'2019-08-25',
                        'arrTime':'21:00',
                        'bookClass':'L',
                        'canChooseSeat':'false',
                        'carInfoSize':0,
                        'depDate':'2019-08-25',
                        'depTime':'18:40',
                        'dstAirPort':{
                            'code':'NAY',
                            'descr':'北京南苑',
                            'name':'北京南苑',
                            'terminal':'--'
                        },
                        'flightNo':'KN5956',
                        'orgAirPort':{
                            'code':'SHA',
                            'descr':'上海虹桥',
                            'name':'上海虹桥',
                            'terminal':'T2'
                        },
                        'passengers':[
                            {
                                'countryTypeCode':'CN',
                                'details':[
                                    {
                                        'amount':'135',
                                        'ancillaryCode':'BAG15KG',
                                        'name':'托运行李15KG',
                                        'quantity':'1',
                                        'status':'--',
                                        'statusTypeCode':'BOOKED',
                                        'unitId':'128239'
                                    }
                                ],
                                'detailsSize':1,
                                'idNumber':'132312334987324',
                                'idTypeCode':'ID',
                                'name':'一样测试',
                                'passType':'ADT',
                                'phoneNumber':'13716827113'
                            },
                            {
                                'countryTypeCode':'CN',
                                'details':[
                                    {
                                        'amount':'225',
                                        'ancillaryCode':'BAG25KG',
                                        'name':'托运行李25KG',
                                        'quantity':'1',
                                        'status':'--',
                                        'statusTypeCode':'BOOKED',
                                        'unitId':'128245'
                                    }
                                ],
                                'detailsSize':1,
                                'idNumber':'132312334987325',
                                'idTypeCode':'ID',
                                'name':'小儿童测试',
                                'passType':'CHD',
                                'phoneNumber':'17602655555'
                            },
                            {
                                'countryTypeCode':'CN',
                                'details':[
                                    {
                                        'amount':'45',
                                        'ancillaryCode':'BAG5KG',
                                        'name':'托运行李5KG',
                                        'quantity':'1',
                                        'status':'--',
                                        'statusTypeCode':'BOOKED',
                                        'unitId':'128249'
                                    }
                                ],
                                'detailsSize':1,
                                'idNumber':'132312334987326',
                                'idTypeCode':'ID',
                                'name':'马天利测试',
                                'passType':'ADT',
                                'phoneNumber':'16600987345'
                            }
                        ],
                        'passengersSize':3,
                        'stopCity':'直达'
                    },
                    {
                        'aircraftType':'73V',
                        'arrDate':'2019-08-26',
                        'arrTime':'08:05',
                        'bookClass':'R',
                        'canChooseSeat':'false',
                        'carInfoSize':0,
                        'depDate':'2019-08-26',
                        'depTime':'07:00',
                        'dstAirPort':{
                            'code':'CIF',
                            'descr':'赤峰',
                            'name':'赤峰',
                            'terminal':'--'
                        },
                        'flightNo':'KN2921',
                        'orgAirPort':{
                            'code':'NAY',
                            'descr':'北京南苑',
                            'name':'北京南苑',
                            'terminal':'--'
                        },
                        'passengers':[
                            {
                                'countryTypeCode':'CN',
                                'details':[
                                    {
                                        'amount':'23',
                                        'ancillaryCode':'BAG5KG',
                                        'name':'托运行李5KG',
                                        'quantity':'1',
                                        'status':'--',
                                        'statusTypeCode':'BOOKED',
                                        'unitId':'128241'
                                    }
                                ],
                                'detailsSize':1,
                                'idNumber':'132312334987324',
                                'idTypeCode':'ID',
                                'name':'一样测试',
                                'passType':'ADT',
                                'phoneNumber':'13716827113'
                            },
                            {
                                'countryTypeCode':'CN',
                                'details':[
                                    {
                                        'amount':'69',
                                        'ancillaryCode':'BAG15KG',
                                        'name':'托运行李15KG',
                                        'quantity':'1',
                                        'status':'--',
                                        'statusTypeCode':'BOOKED',
                                        'unitId':'128243'
                                    }
                                ],
                                'detailsSize':1,
                                'idNumber':'132312334987325',
                                'idTypeCode':'ID',
                                'name':'小儿童测试',
                                'passType':'CHD',
                                'phoneNumber':'17602655555'
                            },
                            {
                                'countryTypeCode':'CN',
                                'detailsSize':0,
                                'idNumber':'132312334987326',
                                'idTypeCode':'ID',
                                'name':'马天利测试',
                                'passType':'ADT',
                                'phoneNumber':'16600987345'
                            }
                        ],
                        'passengersSize':3,
                        'stopCity':'直达'
                    }
                ],
                'rtItinerarysSize':2,
                'taxFeeTotalsSize':0
            },
            'MEAL':{
                'count':'2',
                'goItinerarys':[
                    {
                        'aircraftType':'73V',
                        'arrDate':'2019-08-23',
                        'arrTime':'09:55',
                        'bookClass':'R',
                        'canChooseSeat':'false',
                        'carInfoSize':0,
                        'depDate':'2019-08-23',
                        'depTime':'08:50',
                        'dstAirPort':{
                            'code':'NAY',
                            'descr':'北京南苑',
                            'name':'北京南苑',
                            'terminal':'--'
                        },
                        'flightNo':'KN2922',
                        'orgAirPort':{
                            'code':'CIF',
                            'descr':'赤峰',
                            'name':'赤峰',
                            'terminal':'--'
                        },
                        'passengers':[
                            {
                                'countryTypeCode':'CN',
                                'detailsSize':0,
                                'idNumber':'132312334987324',
                                'idTypeCode':'ID',
                                'name':'一样测试',
                                'passType':'ADT',
                                'phoneNumber':'13716827113'
                            },
                            {
                                'countryTypeCode':'CN',
                                'detailsSize':0,
                                'idNumber':'132312334987325',
                                'idTypeCode':'ID',
                                'name':'小儿童测试',
                                'passType':'CHD',
                                'phoneNumber':'17602655555'
                            },
                            {
                                'countryTypeCode':'CN',
                                'detailsSize':0,
                                'idNumber':'132312334987326',
                                'idTypeCode':'ID',
                                'name':'马天利测试',
                                'passType':'ADT',
                                'phoneNumber':'16600987345'
                            }
                        ],
                        'passengersSize':3,
                        'stopCity':'直达'
                    },
                    {
                        'aircraftType':'73V',
                        'arrDate':'2019-08-23',
                        'arrTime':'17:40',
                        'bookClass':'B',
                        'canChooseSeat':'false',
                        'carInfoSize':0,
                        'depDate':'2019-08-23',
                        'depTime':'15:40',
                        'dstAirPort':{
                            'code':'SHA',
                            'descr':'上海虹桥',
                            'name':'上海虹桥',
                            'terminal':'T2'
                        },
                        'flightNo':'KN5955',
                        'orgAirPort':{
                            'code':'NAY',
                            'descr':'北京南苑',
                            'name':'北京南苑',
                            'terminal':'--'
                        },
                        'passengers':[
                            {
                                'countryTypeCode':'CN',
                                'details':[
                                    {
                                        'amount':'12',
                                        'ancillaryCode':'TC1M',
                                        'name':'黄焖鸡米饭套餐',
                                        'quantity':'1',
                                        'status':'--',
                                        'statusTypeCode':'BOOKED',
                                        'unitId':'128242'
                                    }
                                ],
                                'detailsSize':1,
                                'idNumber':'132312334987324',
                                'idTypeCode':'ID',
                                'name':'一样测试',
                                'passType':'ADT',
                                'phoneNumber':'13716827113'
                            },
                            {
                                'countryTypeCode':'CN',
                                'details':[
                                    {
                                        'amount':'12',
                                        'ancillaryCode':'TC1M',
                                        'name':'黄焖鸡米饭套餐',
                                        'quantity':'1',
                                        'status':'--',
                                        'statusTypeCode':'BOOKED',
                                        'unitId':'128247'
                                    }
                                ],
                                'detailsSize':1,
                                'idNumber':'132312334987325',
                                'idTypeCode':'ID',
                                'name':'小儿童测试',
                                'passType':'CHD',
                                'phoneNumber':'17602655555'
                            },
                            {
                                'countryTypeCode':'CN',
                                'detailsSize':0,
                                'idNumber':'132312334987326',
                                'idTypeCode':'ID',
                                'name':'马天利测试',
                                'passType':'ADT',
                                'phoneNumber':'16600987345'
                            }
                        ],
                        'passengersSize':3,
                        'stopCity':'直达'
                    }
                ],
                'goItinerarysSize':2,
                'goodsName':'餐食',
                'groupCode':'MEAL',
                'rtItinerarys':[
                    {
                        'aircraftType':'73V',
                        'arrDate':'2019-08-25',
                        'arrTime':'21:00',
                        'bookClass':'L',
                        'canChooseSeat':'false',
                        'carInfoSize':0,
                        'depDate':'2019-08-25',
                        'depTime':'18:40',
                        'dstAirPort':{
                            'code':'NAY',
                            'descr':'北京南苑',
                            'name':'北京南苑',
                            'terminal':'--'
                        },
                        'flightNo':'KN5956',
                        'orgAirPort':{
                            'code':'SHA',
                            'descr':'上海虹桥',
                            'name':'上海虹桥',
                            'terminal':'T2'
                        },
                        'passengers':[
                            {
                                'countryTypeCode':'CN',
                                'detailsSize':0,
                                'idNumber':'132312334987324',
                                'idTypeCode':'ID',
                                'name':'一样测试',
                                'passType':'ADT',
                                'phoneNumber':'13716827113'
                            },
                            {
                                'countryTypeCode':'CN',
                                'detailsSize':0,
                                'idNumber':'132312334987325',
                                'idTypeCode':'ID',
                                'name':'小儿童测试',
                                'passType':'CHD',
                                'phoneNumber':'17602655555'
                            },
                            {
                                'countryTypeCode':'CN',
                                'detailsSize':0,
                                'idNumber':'132312334987326',
                                'idTypeCode':'ID',
                                'name':'马天利测试',
                                'passType':'ADT',
                                'phoneNumber':'16600987345'
                            }
                        ],
                        'passengersSize':3,
                        'stopCity':'直达'
                    },
                    {
                        'aircraftType':'73V',
                        'arrDate':'2019-08-26',
                        'arrTime':'08:05',
                        'bookClass':'R',
                        'canChooseSeat':'false',
                        'carInfoSize':0,
                        'depDate':'2019-08-26',
                        'depTime':'07:00',
                        'dstAirPort':{
                            'code':'CIF',
                            'descr':'赤峰',
                            'name':'赤峰',
                            'terminal':'--'
                        },
                        'flightNo':'KN2921',
                        'orgAirPort':{
                            'code':'NAY',
                            'descr':'北京南苑',
                            'name':'北京南苑',
                            'terminal':'--'
                        },
                        'passengers':[
                            {
                                'countryTypeCode':'CN',
                                'detailsSize':0,
                                'idNumber':'132312334987324',
                                'idTypeCode':'ID',
                                'name':'一样测试',
                                'passType':'ADT',
                                'phoneNumber':'13716827113'
                            },
                            {
                                'countryTypeCode':'CN',
                                'detailsSize':0,
                                'idNumber':'132312334987325',
                                'idTypeCode':'ID',
                                'name':'小儿童测试',
                                'passType':'CHD',
                                'phoneNumber':'17602655555'
                            },
                            {
                                'countryTypeCode':'CN',
                                'detailsSize':0,
                                'idNumber':'132312334987326',
                                'idTypeCode':'ID',
                                'name':'马天利测试',
                                'passType':'ADT',
                                'phoneNumber':'16600987345'
                            }
                        ],
                        'passengersSize':3,
                        'stopCity':'直达'
                    }
                ],
                'rtItinerarysSize':2,
                'taxFeeTotalsSize':0
            }
        },
        'componentsSize':3,
        'contact':{
            'name':'刘健',
            'telNumber':'17602656463'
        },
        'iOrD':'D',
        'isAnnualOrder':'false',
        'isChangeOrder':false,
        'isGmjcOrder':false,
        'orderAmount':'10553',
        'orderCreateTime':'2019-07-23 18:07:37',
        'orderMode':'2',
        'orderNo':'20J7NYCPGZC',
        'orderStatus':'已支付',
        'orderTypeCode':'NORMALFARE',
        'payInfos':[
            {
                'bussinessCode':'H5',
                'isPayForTicket':'true',
                'payAmount':'10553',
                'payType':'虚拟支付',
                'paytime':'2019-07-23 18:08',
                'transactionNo':'ATGJ7N1BPJGM4'
            }
        ],
        'payInfosSize':1,
        'statusTypeCode':'PAYED',
        'tripType':'ROUNDTRIP'
    }
}