/**
 * @description 路由相关
 *  */
// 修改路由
export const CHANGE_ROUTE = 'CHANGE/ROUTE';
// 修改loading状态
export const CHANGE_LOADING = 'CHANGE/LOADING';
// 修改 headername
export const UPDATE_HEADERNAME = 'UPDATE/HEADERNAME';
// 设置login状态
export const CHECK_LOGIN_STATUS = 'CHECK_LOGIN_STATUS';
// 设置用户名
export const SET_USER_NAME = 'SET_USER_NAME';

//订单详情
export const QUERY_ORDER_DETAIL = 'QUERY_ORDER_DETAIL';
export const CANCEL_ORDER = 'CANCEL_ORDER';
export const REQUEST_INSURANCE_REFUND = 'REQUEST_INSURANCE_REFUND';
export const REQUEST_ORDER_REFUND = 'REQUEST_ORDER_REFUND';
export const CHECK_ORDER_ERROR_REFUND = 'CHECK_ORDER_ERROR_REFUND';

//退票相关
export const RD_SAVE_ORDER_REFUND_CHECKED_PSG = 'RD_SAVE_ORDER_REFUND_CHECKED_PSG';

//改升相关
export const CU_SAVE_ORDER_CHANGE_CHECKED_PSG = 'CU_SAVE_ORDER_CHANGE_CHECKED_PSG';
export const CU_SAVE_ORDER_CHANGE_CHECKED_FLIGHT = 'CU_SAVE_ORDER_CHANGE_CHECKED_FLIGHT';
